### ISSUE TITLE
Support/Set UXP-version for UXP: 8.0.1 (Adobe InDesign v20.0)

### ISSUE THREAD

**Issue by zaphodbeeblebroxx** [jardicc/vscode-uxp-validator#17]
"Set version" doesn't support the newest UXP-Version 8.0.1

**Comment by jardicc** [comment]
Yes... I work on that... I think I have all the changes ready for release.

I am waiting for some additional info. But I don't see it coming. I think I will state that scale and rotate work since UXP 8.0 even it is not true because I don't want to reinstall PS X-times to do the detective work.

But if someone else has the exact version and is sure about that I can change it.

![image](https://github.com/user-attachments/assets/d6a35a2d-6621-462d-b730-46bed1df0165)

**Comment by zaphodbeeblebroxx** [comment]
adobe documentation (if there is any) is a kind of mystery.

**Comment by jardicc** [comment]
CSS is documented only up to UXP 3.0 ...after that only changelogs and some articles mention new features if we are lucky.

**Comment by jardicc** [comment]
Done: https://github.com/jardicc/vscode-uxp-validator/releases/tag/v1.2.0
